ODS RTF FILE ='M:\econ304\hetero.rtf';
data ht;
infile 'M:\econ304\maxim.csv' dlm = ',';
input trump clinton other hs c y white black am asian native hispanic; high_school_ = hs *100;
bachelors_ = c*100;
income_ = y;
black_ = black*100;
hispanic_ = hispanic*100;
pct = 100*trump/(trump + clinton + other); run;
proc reg;
model pct = high_school_ bachelors_ black_ hispanic_/spec hccmethod=3 white; output out=two residual = res;
run;
data hetero;
set two;
resq = res*res;
run;
proc reg data=hetero;
model resq = high_school bachelors_ black_ hispanic_;
run;
ODS RTF CLOSE;